# Generated by Django 3.0.4 on 2020-04-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0003_auto_20200413_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articalecontact',
            old_name='Phone',
            new_name='phone',
        ),
    ]
