# Generated by Django 3.0.4 on 2020-04-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0008_auto_20200414_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categorys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_categorys', to='tapp.BlogCategory'),
        ),
    ]
